version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: case_management_db
    environment:
      POSTGRES_DB: case_management_db
      POSTGRES_USER: case_user
      POSTGRES_PASSWORD: case_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: