spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/case_management_db
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    baseline-on-migrate: true
    baseline-version: 0
  mail:
    host: smtp.mail.ru
    port: 465
    username: luk-2004@mail.ru
    password: ${MAIL_PASSWORD}
    protocol: smtps
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
            port: 465
  task:
    execution:
      pool:
        core-size: 5
        max-size: 10
        queue-capacity: 25
  application:
    name: case-management


jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}

server:
  port: 8080

logging:
  level:
    org.springframework.security: DEBUG
    org.example.casemanagement: DEBUG 