spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/case_management_db
    username: case_user
    password: case_password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    baseline-on-migrate: true
    baseline-version: 0
  mail:
    host: smtp.mail.ru
    port: 465
    username: luk-2004@mail.ru
    password: wUhgbZ4HEfcJwYGWm6u1
    protocol: smtps
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
            port: 465
  task:
    execution:
      pool:
        core-size: 5
        max-size: 10
        queue-capacity: 25
  application:
    name: case-management

jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  expiration: 86400000

server:
  port: 8080

logging:
  level:
    org.springframework.security: DEBUG
    org.example.casemanagement: DEBUG 